#!/bin/bash
# chkconfig: 45 95 20
# description: Mint
# Start/Stops the Mint service
# processname: mint
# Source function library
. /etc/rc.d/init.d/functions
daemon --user=redbox /opt/mint/server/tf.sh $1
echo